### ISSUE TITLE
Repeated executions

### ISSUE THREAD

**Issue by paolorr** [Azure/azure-webjobs-sdk-extensions#40]
I'm using TimerTrigger to run a job daily at 18:00 (6pm UTC -2:00) but I noticed the job sometimes runs twice as shown in the log

In this case it runs twice due to website restart, which I don't know why, because it's set Always On
```
[02/15/2016 19:59:59 > f70569: INFO] Executing: 'Functions.SendPublishedInspections' - Reason: 'Timer fired at 2016-02-15T17:59:58.6655227-02:00'
[02/15/2016 20:00:00 > f70569: INFO] Executed: 'Functions.SendPublishedInspections' (Succeeded)
[02/15/2016 20:42:53 > 9dad03: SYS INFO] Status changed to Starting
...
[02/15/2016 20:43:08 > 9dad03: INFO] Job host started
[02/15/2016 20:45:45 > f70569: SYS INFO] WebJob is stopping due to website shutting down
[02/15/2016 20:45:45 > f70569: SYS INFO] Status changed to Stopping
[02/15/2016 20:45:46 > f70569: INFO] Job host stopped
[02/15/2016 20:45:47 > f70569: SYS INFO] Status changed to Success
[02/15/2016 20:45:47 > f70569: SYS INFO] Status changed to Stopped
[02/15/2016 20:46:09 > 9dad03: INFO] Executing: 'Functions.SendPublishedInspections' - Reason: 'Timer fired at 2016-02-15T18:46:09.0790525-02:00'
[02/15/2016 20:46:10 > 9dad03: INFO] Executed: 'Functions.SendPublishedInspections' (Succeeded)
```

In this case it runs twice due to webjob restart, which I also don't know why, because the website hasn't restarted. Notice that the first execution was ok, at 17:59, but the second execution was at 22:45, 4 hours after the scheduled time
```
[02/18/2016 19:59:59 > 2627e8: INFO] Executing: 'Functions.SendPublishedInspections' - Reason: 'Timer fired at 2016-02-18T17:59:59.7431098-02:00'
[02/18/2016 20:00:00 > 2627e8: INFO] Executed: 'Functions.SendPublishedInspections' (Succeeded)
[02/19/2016 00:44:44 > 2627e8: SYS INFO] Status changed to Starting
..
[02/19/2016 00:44:51 > 2627e8: INFO] Job host started
[02/19/2016 00:45:52 > 2627e8: INFO] Executing: 'Functions.SendPublishedInspections' - Reason: 'Timer fired at 2016-02-18T22:45:51.8263891-02:00'
[02/19/2016 00:45:53 > 2627e8: INFO] Executed: 'Functions.SendPublishedInspections' (Succeeded)
```

In this case it simply runs twice in a row
```
[02/16/2016 19:59:56 > 9dad03: INFO] Executing: 'Functions.SendPublishedInspections' - Reason: 'Timer fired at 2016-02-16T17:59:56.5463054-02:00'
[02/16/2016 19:59:57 > 9dad03: INFO] Executed: 'Functions.SendPublishedInspections' (Succeeded)
[02/16/2016 20:00:00 > 9dad03: INFO] Executing: 'Functions.SendPublishedInspections' - Reason: 'Timer fired at 2016-02-16T18:00:00.0280857-02:00'
[02/16/2016 20:00:00 > 9dad03: INFO] Executed: 'Functions.SendPublishedInspections' (Succeeded)
```

Here is my scheduled config

```
    public class PublishedInspectionsSchedule : WeeklySchedule
    {
        public PublishedInspectionsSchedule() :
            base()
        {
            var configHours = ConfigurationManager.AppSettings["PublishedInspectionsSchedule"];

            if (!string.IsNullOrWhiteSpace(configHours))
            {
                var times = configHours.Split(',').Select(x => TimeSpan.Parse(x)).OrderBy(p => p).ToList();
                foreach (var item in times)
                {
                    Add(DayOfWeek.Monday, item);
                    Add(DayOfWeek.Tuesday, item);
                    Add(DayOfWeek.Wednesday, item);
                    Add(DayOfWeek.Thursday, item);
                    Add(DayOfWeek.Friday, item);
                    Add(DayOfWeek.Saturday, item);
                    Add(DayOfWeek.Sunday, item);
                }
            }
        }
    }
```

Is there some kind of configuration that I can set a interval of execution, e.g., 1 minute before and 1 minute after the scheduled time? If the job restarts, the second time would be out of the interval and won't run.

Any ideia why the job is restarting?

Any ideia why it ran twice in a row?

**Comment by BrianVallelunga** [comment]
I'm seeing similar behavior on a frequent basis. I suggest you check the timerInfo.IsPastDue property. For me, that is set to true when the firing occurs at odd times. Unfortunately, it also seems to be incorrect, so I'm just exiting my job immediately when that is true.

**Comment by mathewc** [comment]
Thanks guys. It does seem like there is some issue, and I'd like to track it down. What version are you guys running? In the current prerelease build, we've made some bug fixes to TimerTrigger that may address this issue. If you have a consistent repro for this issue, you might try the updated build to see if it fixes things (prerelease instructions [here](https://github.com/Azure/azure-webjobs-sdk/wiki/%22Nightly%22-Builds)).

**Comment by mattwoberts** [comment]
Just to add to this..

I've just installed the azure skd extensions, and I've got a bunch of TimerTriggers. 

One of them runs every hours, but when I restarted my webjob earlier today, it ran on startup. After that rogue run, it ran every hour as it should.

Here's my functin signature:

`public static void ExecuteXXXJob([TimerTrigger("20 0 * * * *", RunOnStartup = false)] TimerInfo timerInfo, TextWriter log)`

it ran at 20:00pm, then I restarted my webjobs, and then it rain again:

`	Executing: 'SlackPostJob.ExecuteSlackPostJob' - Reason: 'Timer fired at 2016-03-07T20:10:48.8273409+00:00'`

**Comment by mathewc** [comment]
What version are you running - are you running the latest pre-release linked above?

**Comment by mattwoberts** [comment]
@mathewc I'm not using the pre-release bits no, this is just based off pulling the latest stable bits from nuget. It's not happened since the time I reported it though, so it's going to be a tricky one to test!

**Comment by mattwoberts** [comment]
@mathewc Eek, just had this happen again with 3 triggers firing on startup - now I can see the pattern.

What happens, is I did a deployment at around lunch time. Any [TimerTrigger] jobs that had executed this morning one or more times, were then fired off when I did a deployment. For me a deployment is done with deployment slots, like this:

1) Push to a repo that auto deploys to  my staging slot
2) Test my staging slot
3) Swap into production.

So should I try the pre-release? Is it safe for production?

**Comment by BrianVallelunga** [comment]
I'm running the latest stable version as well. If you can publish a pre-release version to nuget, I can try that.

**Comment by mattwoberts** [comment]
Hi

I just tried to include the nightly nuget feed to VS, but it did't work - if you look at the feed URL for the nightlies, it's currently empty (https://www.myget.org/F/azure-appservice/api/v2)

Cheers

**Comment by mattwoberts** [comment]
Since my issue is related to swapping deployment slots, it looks like it might be related to this:

https://github.com/Azure/azure-webjobs-sdk-extensions/issues/56

I'll try specifying a different job id for each deployment slot

**Comment by agnauck** [comment]
I have the same problem. I had to publish one of my jobs several times today. The timer which should run only once a day fired immediately after each publish. I think also once per instance. The function has the Singleton attribute with Listener mode on it.

**Comment by mathewc** [comment]
@mattwoberts The prerelease packages are on Myget here http://myget.org/gallery/azure-appservice. Looks like they may have updated their feed URL to https://www.myget.org/F/azure-appservice/api/v3/index.json.

**Comment by shyamal890** [comment]
Facing the same issue. I have a timer that runs every Monday and sends emails to customers. Whenever, web app is started and stopped (continuous build) timer is triggered again, annoying customers with repeated emails. Hope this issue is solved soon. Meanwhile is there a short-term solution to this?

Here is my implementation:
```
        [Singleton]
        public static async Task StartOfWeek([TimerTrigger("0 0 0 * * Sun",RunOnStartup =false)]TimerInfo info)
        {//Sends emails} 
```

**Comment by mattwoberts** [comment]
Still having this (repeated runs). After some awesome help from @mathewc it looked liked in my case it might be related to having one of my staging slots running in parallel, but I've totally disabled my staging slots and I'm still seeing this happen. The latest bits on the myget feed don't make a difference either.

I'm trying to drill into the issue more - the only thing I've noticed so far is that the blob leases say they failed to acquire when the job first runs, then are acquired later - this is odd, I'm wondering why they'd fail to be acquired since nothing else is running....

Anyway - once acquired, the verbose logging tells me they're going to run at the correct times, and then they run twice at those times.

Just for clarity - it seems there are 2 issues people are reporting:

1) The issue of the job running twice when at its run time.
2) The issue of the job running when the webjob starts up, even with the RunAtStartup set to false.

I'll add more info if I find any

**Comment by Thnslj** [comment]
@mattwoberts I think I have found an explanation to issue #2 
https://github.com/Azure/azure-webjobs-sdk-extensions/issues/132

**Comment by mattwoberts** [comment]
Awesome stuff, looks like progress is coming on now with this :)

**Comment by ealsur** [comment]
+1 Facing the same issue on a Continuous Integrated App Service on each deploy. There are no Staging slots. But it looks like for TimerTriggers, the RunOnStartup attribute doesn't seem to work.

**Comment by brettsam** [comment]
This is now in and the new package is on MyGet. Give it a try and let us know if you find any issues. Thanks!
